name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build project
        run: docker run --rm -v $PWD/app:/app composer@sha256:d374b2e1f715621e9d9929575d6b35b11cf4a6dc237d4a08f2e6d1611f534675 install
      - name: Tar project files
        run: tar -czvf project.tar.gz app/
      - name: Upload project artifacts
        uses: actions/upload-artifact@v2
        with:
          path: project.tar.gz
          name: project
